# Generated by Django 2.1 on 2018-08-13 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name', max_length=55)),
                ('seen', models.BooleanField(default=False, help_text='Has this notification been seen?')),
                ('seen_on', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_owner', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_reciever', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name', max_length=55)),
                ('completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name', max_length=55)),
                ('description', models.TextField(help_text='Description')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('LinkedTaskList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.Task')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskComment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name', max_length=55)),
                ('description', models.TextField(help_text='Description')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskList_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskListComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name', max_length=55)),
                ('description', models.TextField(help_text='Description')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('LinkedTaskList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.TaskList')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskListComment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(help_text='#TODO, find out what this means.', max_length=55)),
                ('LinkedTaskList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.TaskList')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRelation_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='LinkedTaskList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.TaskList'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
