# Generated by Django 2.1 on 2018-08-13 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
