# Generated by Django 2.1 on 2018-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0002_auto_20180813_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasklistcomment',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
