# Generated by Django 2.1 on 2018-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0004_auto_20180814_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='title',
            field=models.CharField(help_text='Task name', max_length=55),
        ),
    ]
