# Generated by Django 2.1 on 2018-08-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0005_auto_20180814_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistrelation',
            name='role',
            field=models.CharField(default='guest', help_text='#TODO, find out what this means.', max_length=55),
        ),
    ]
