# Generated by Django 2.1 on 2018-08-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0006_auto_20180816_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlistrelation',
            name='views',
        ),
    ]
