# Generated by Django 2.1 on 2018-08-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0009_remove_notification_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='changes',
            field=models.CharField(default='', help_text='Plaintext list of changes', max_length=250),
        ),
    ]
