# Generated by Django 2.1 on 2018-08-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0010_notification_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deep_link_url',
            field=models.CharField(default='', help_text='name', max_length=250),
        ),
    ]
